from distutils.core import setup

setup(
    name='UWClassEvalScrapper',
    version='1.0',
    packages=['venv.lib.python3.6.site-packages.PIL', 'venv.lib.python3.6.site-packages.bs4',
              'venv.lib.python3.6.site-packages.bs4.tests', 'venv.lib.python3.6.site-packages.bs4.builder',
              'venv.lib.python3.6.site-packages.xdg', 'venv.lib.python3.6.site-packages.cffi',
              'venv.lib.python3.6.site-packages.idna', 'venv.lib.python3.6.site-packages.yaml',
              'venv.lib.python3.6.site-packages.wheel', 'venv.lib.python3.6.site-packages.wheel.cli',
              'venv.lib.python3.6.site-packages.debian', 'venv.lib.python3.6.site-packages.certifi',
              'venv.lib.python3.6.site-packages.jeepney', 'venv.lib.python3.6.site-packages.jeepney.tests',
              'venv.lib.python3.6.site-packages.jeepney.integrate', 'venv.lib.python3.6.site-packages.keyring',
              'venv.lib.python3.6.site-packages.keyring.util', 'venv.lib.python3.6.site-packages.keyring.tests',
              'venv.lib.python3.6.site-packages.keyring.tests.backends',
              'venv.lib.python3.6.site-packages.keyring.backends', 'venv.lib.python3.6.site-packages.olefile',
              'venv.lib.python3.6.site-packages.pexpect', 'venv.lib.python3.6.site-packages.urllib3',
              'venv.lib.python3.6.site-packages.urllib3.util', 'venv.lib.python3.6.site-packages.urllib3.contrib',
              'venv.lib.python3.6.site-packages.urllib3.contrib._securetransport',
              'venv.lib.python3.6.site-packages.urllib3.packages',
              'venv.lib.python3.6.site-packages.urllib3.packages.backports',
              'venv.lib.python3.6.site-packages.urllib3.packages.ssl_match_hostname',
              'venv.lib.python3.6.site-packages.httplib2', 'venv.lib.python3.6.site-packages.keyrings',
              'venv.lib.python3.6.site-packages.keyrings.alt', 'venv.lib.python3.6.site-packages.requests',
              'venv.lib.python3.6.site-packages.pycparser', 'venv.lib.python3.6.site-packages.pycparser.ply',
              'venv.lib.python3.6.site-packages.reportlab', 'venv.lib.python3.6.site-packages.reportlab.lib',
              'venv.lib.python3.6.site-packages.reportlab.pdfgen', 'venv.lib.python3.6.site-packages.reportlab.pdfbase',
              'venv.lib.python3.6.site-packages.reportlab.graphics',
              'venv.lib.python3.6.site-packages.reportlab.graphics.charts',
              'venv.lib.python3.6.site-packages.reportlab.graphics.barcode',
              'venv.lib.python3.6.site-packages.reportlab.graphics.samples',
              'venv.lib.python3.6.site-packages.reportlab.graphics.widgets',
              'venv.lib.python3.6.site-packages.reportlab.platypus', 'venv.lib.python3.6.site-packages.ptyprocess',
              'venv.lib.python3.6.site-packages.setuptools', 'venv.lib.python3.6.site-packages.setuptools.extern',
              'venv.lib.python3.6.site-packages.setuptools._vendor',
              'venv.lib.python3.6.site-packages.setuptools._vendor.packaging',
              'venv.lib.python3.6.site-packages.setuptools.command', 'venv.lib.python3.6.site-packages.cryptography',
              'venv.lib.python3.6.site-packages.cryptography.x509',
              'venv.lib.python3.6.site-packages.cryptography.hazmat',
              'venv.lib.python3.6.site-packages.cryptography.hazmat.backends',
              'venv.lib.python3.6.site-packages.cryptography.hazmat.backends.openssl',
              'venv.lib.python3.6.site-packages.cryptography.hazmat.bindings',
              'venv.lib.python3.6.site-packages.cryptography.hazmat.bindings.openssl',
              'venv.lib.python3.6.site-packages.cryptography.hazmat.primitives',
              'venv.lib.python3.6.site-packages.cryptography.hazmat.primitives.kdf',
              'venv.lib.python3.6.site-packages.cryptography.hazmat.primitives.ciphers',
              'venv.lib.python3.6.site-packages.cryptography.hazmat.primitives.twofactor',
              'venv.lib.python3.6.site-packages.cryptography.hazmat.primitives.asymmetric',
              'venv.lib.python3.6.site-packages.debian_bundle', 'venv.lib.python3.6.site-packages.pkg_resources',
              'venv.lib.python3.6.site-packages.pkg_resources.extern',
              'venv.lib.python3.6.site-packages.pkg_resources._vendor',
              'venv.lib.python3.6.site-packages.pkg_resources._vendor.packaging',
              'venv.lib.python3.6.site-packages.secretstorage', 'venv.lib64.python3.6.site-packages.PIL',
              'venv.lib64.python3.6.site-packages.bs4', 'venv.lib64.python3.6.site-packages.bs4.tests',
              'venv.lib64.python3.6.site-packages.bs4.builder', 'venv.lib64.python3.6.site-packages.xdg',
              'venv.lib64.python3.6.site-packages.cffi', 'venv.lib64.python3.6.site-packages.idna',
              'venv.lib64.python3.6.site-packages.yaml', 'venv.lib64.python3.6.site-packages.wheel',
              'venv.lib64.python3.6.site-packages.wheel.cli', 'venv.lib64.python3.6.site-packages.debian',
              'venv.lib64.python3.6.site-packages.certifi', 'venv.lib64.python3.6.site-packages.jeepney',
              'venv.lib64.python3.6.site-packages.jeepney.tests',
              'venv.lib64.python3.6.site-packages.jeepney.integrate', 'venv.lib64.python3.6.site-packages.keyring',
              'venv.lib64.python3.6.site-packages.keyring.util', 'venv.lib64.python3.6.site-packages.keyring.tests',
              'venv.lib64.python3.6.site-packages.keyring.tests.backends',
              'venv.lib64.python3.6.site-packages.keyring.backends', 'venv.lib64.python3.6.site-packages.olefile',
              'venv.lib64.python3.6.site-packages.pexpect', 'venv.lib64.python3.6.site-packages.urllib3',
              'venv.lib64.python3.6.site-packages.urllib3.util', 'venv.lib64.python3.6.site-packages.urllib3.contrib',
              'venv.lib64.python3.6.site-packages.urllib3.contrib._securetransport',
              'venv.lib64.python3.6.site-packages.urllib3.packages',
              'venv.lib64.python3.6.site-packages.urllib3.packages.backports',
              'venv.lib64.python3.6.site-packages.urllib3.packages.ssl_match_hostname',
              'venv.lib64.python3.6.site-packages.httplib2', 'venv.lib64.python3.6.site-packages.keyrings',
              'venv.lib64.python3.6.site-packages.keyrings.alt', 'venv.lib64.python3.6.site-packages.requests',
              'venv.lib64.python3.6.site-packages.pycparser', 'venv.lib64.python3.6.site-packages.pycparser.ply',
              'venv.lib64.python3.6.site-packages.reportlab', 'venv.lib64.python3.6.site-packages.reportlab.lib',
              'venv.lib64.python3.6.site-packages.reportlab.pdfgen',
              'venv.lib64.python3.6.site-packages.reportlab.pdfbase',
              'venv.lib64.python3.6.site-packages.reportlab.graphics',
              'venv.lib64.python3.6.site-packages.reportlab.graphics.charts',
              'venv.lib64.python3.6.site-packages.reportlab.graphics.barcode',
              'venv.lib64.python3.6.site-packages.reportlab.graphics.samples',
              'venv.lib64.python3.6.site-packages.reportlab.graphics.widgets',
              'venv.lib64.python3.6.site-packages.reportlab.platypus', 'venv.lib64.python3.6.site-packages.ptyprocess',
              'venv.lib64.python3.6.site-packages.setuptools', 'venv.lib64.python3.6.site-packages.setuptools.extern',
              'venv.lib64.python3.6.site-packages.setuptools._vendor',
              'venv.lib64.python3.6.site-packages.setuptools._vendor.packaging',
              'venv.lib64.python3.6.site-packages.setuptools.command',
              'venv.lib64.python3.6.site-packages.cryptography', 'venv.lib64.python3.6.site-packages.cryptography.x509',
              'venv.lib64.python3.6.site-packages.cryptography.hazmat',
              'venv.lib64.python3.6.site-packages.cryptography.hazmat.backends',
              'venv.lib64.python3.6.site-packages.cryptography.hazmat.backends.openssl',
              'venv.lib64.python3.6.site-packages.cryptography.hazmat.bindings',
              'venv.lib64.python3.6.site-packages.cryptography.hazmat.bindings.openssl',
              'venv.lib64.python3.6.site-packages.cryptography.hazmat.primitives',
              'venv.lib64.python3.6.site-packages.cryptography.hazmat.primitives.kdf',
              'venv.lib64.python3.6.site-packages.cryptography.hazmat.primitives.ciphers',
              'venv.lib64.python3.6.site-packages.cryptography.hazmat.primitives.twofactor',
              'venv.lib64.python3.6.site-packages.cryptography.hazmat.primitives.asymmetric',
              'venv.lib64.python3.6.site-packages.debian_bundle', 'venv.lib64.python3.6.site-packages.pkg_resources',
              'venv.lib64.python3.6.site-packages.pkg_resources.extern',
              'venv.lib64.python3.6.site-packages.pkg_resources._vendor',
              'venv.lib64.python3.6.site-packages.pkg_resources._vendor.packaging',
              'venv.lib64.python3.6.site-packages.secretstorage'],
    url='https://github.com/bryoco/UWClassEvalScrapper',
    license='Apache License 2.0',
    author='ryocown',
    author_email='',
    description=''
)
